name: TDR Deploy Auth Server
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true

run-name: Deploying Auth Server ${{inputs.to-deploy}} to ${{inputs.environment}}  
permissions:
  contents: read
jobs:
  deploy:
    permissions:
      id-token: write
      contents: write
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_deploy.yml@2d29c2e83fbaba6554c1e0d8c0b45d2015d610b2 # v0.0.41
    with:
      service: keycloak
      image-name: auth-server
      environment: ${{ github.event.inputs.environment }}
      to-deploy: ${{ github.event.inputs.to-deploy }}
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  push-update-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubActionsRoleMgmt
          aws-region: eu-west-2
          role-session-name: APIECRLogin
      - name: Login to ECR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com
      - run: |
          docker build --pull -f Dockerfile-update -t ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/keycloak-update:${{ github.event.inputs.environment }} .
          docker push ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/keycloak-update:${{ github.event.inputs.environment }}          
